export namespace MaxModules {
  const modules = [
    {
      title: "Dashboard",
      id: 0,
      defaultPath: "/dashboard",
      moreOptions: false,
      globalSearchKey: "global",
      childrens: [],
      dontShow: true,
      allUsersAllow: false,
    },
    {
      title: "Out Patients",
      id: 2,
      defaultPath: "/out-patients",
      moreOptions: true,
      childrens: [
        {
          id: -1,
          title: "Registration",
          defaultPath: "registration",
          moreOptions: true,
          tenentPath: "/out-patients",
          childrens: [
            {
              id: 60,
              title: "OP Registration",
              defaultPath: "/registration/op-registration",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 61,
              title: "Find Patient",
              defaultPath: "/registration/find-patient",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 460,
              title: "Duplicate Reg Merging",
              defaultPath: "/registration/dup-reg-merging",
              globalSearchKey: "merge",
              allUsersAllow: false,
            },
            {
              id: 461,
              title: "Registration Unmerging",
              defaultPath: "/registration/registration-unmerging",
              globalSearchKey: "unmerge",
              allUsersAllow: false,
            },
            {
              id: 115,
              title: "Registration Modification",
              defaultPath: "/registration/op-registration",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 595,
              title: "OP Patient Reg Approval List",
              defaultPath: "/registration/op-reg-approval",
              globalSearchKey: "opapproval",
              allUsersAllow: false,
            },
            {
              id: 597,
              title: "Hot Listing Approval",
              defaultPath: "/registration/hot-listing-approval",
              globalSearchKey: "opapproval",
              allUsersAllow: false,
            },
            {
              id: 118,
              title: "Bulk Upload Registration",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 119,
              title: "Search Patient Admit/Discharge",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 120,
              title: "Report for Bulk Upload Reg",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 121,
              title: "For Ambulance and Reg Charges",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 122,
              title: "Blood Group Entry",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
          ],
        },
        {
          id: -1,
          title: "Out Patient Billing",
          defaultPath: "out-patient-billing",
          tenentPath: "/out-patients",
          childrens: [
            {
              id: 62,
              title: "Out Patient Billing",
              defaultPath: "/out-patient-billing/",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 64,
              title: "Deposit",
              defaultPath: "/out-patient-billing/deposit",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 63,
              title: "Bill Details",
              defaultPath: "/out-patient-billing/details",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 214,
              title: "Online Generated OP Bills",
              defaultPath: "/out-patient-billing/online-op-bill",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 215,
              title: "OP Order Request",
              defaultPath: "/out-patient-billing/op-order-request",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 216,
              title: "Miscellaneous Billing",
              defaultPath: "/out-patient-billing/miscellaneous-billing",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 217,
              title: "Initiate Deposit",
              defaultPath: "/out-patient-billing/initiate-deposit",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 218,
              title: "OP Refund Approval",
              defaultPath: "/out-patient-billing/op-refund-approval",
              globalSearchKey: "opapproval",
              allUsersAllow: false,
            },
            {
              id: 219,
              title: "DMG Mapping",
              defaultPath: "/out-patient-billing/dmg-mapping",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 62,
              title: "Post Discharge Follow Up Billing",
              defaultPath:
                "/out-patient-billing/post-discharge-follow-up-billing",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            // dispatch
            {
              id: 222,
              title: "Expired Patient Check",
              defaultPath: "/out-patient-billing/expired-patient-check",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
          ],
          moreOptions: true,
        },
        {
          id: -1,
          title: "ACD",
          tenentPath: "/out-patients",
          defaultPath: "/acd/investigation-orders",
          childrens: [],
          moreOptions: false,
        },
        {
          id: -1,
          title: "Patient History",
          tenentPath: "/out-patients",
          defaultPath: "/patient-history",
          childrens: [],
          moreOptions: false,
        },
        {
          id: -1,
          title: "Configure",
          tenentPath: "/out-patients",
          defaultPath: "",
          childrens: [
            {
              id: 223,
              title: "Regenerate RIS Message",
              defaultPath: "/configure/RIS",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 224,
              title: "Regenerate LIMS Message",
              defaultPath: "/configure/LIMS",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
          ],
          moreOptions: true,
        },
        {
          id: -1,
          title: "QMS",
          tenentPath: "/out-patients",
          defaultPath: "/qms",
          childrens: [],
          moreOptions: false,
        },
        {
          id: -1,
          title: "Staff Dependents",
          tenentPath: "/out-patients",
          defaultPath: "/staff-dept",
          childrens: [],
          moreOptions: false,
        },
        {
          id: -1,
          title: "Employee Sponsor Tagging",
          tenentPath: "/out-patients",
          defaultPath: "/employee-sponsor-tagging",
          childrens: [],
          moreOptions: false,
          locationSpecific: [{ loc: 69 }],
          globalSearchKey: "employeesponsor",
        },
        {
          id: -1,
          title: "Reports",
          tenentPath: "/out-patients",
          defaultPath: "report",
          childrens: [
            {
              id: 83,
              title: "Doctor Schedule",
              defaultPath: "/report/prompt-report/doctorSchedule",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 66,
              title: "Cash Scroll",
              defaultPath: "/out-patient-billing/cash-scroll",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 85,
              title: "Happy Family Report",
              defaultPath:
                "/report-multiple/prompt-report/HappyFamilyPlanAllocationReport",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 88,
              title: "Equipment Schedule",
              defaultPath: "/report/prompt-report/equipmentSchedule",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 89,
              title: "General OPD Scroll Report",
              defaultPath: "/report/prompt-report/GeneralOPDReport",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 916,
              title: "Expired Patient Report",
              defaultPath:
                "/report/prompt-report/CRPExpiredPatientDetailReport",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 917,
              title: "Monthly OP Consultation Report",
              defaultPath:
                "/out-patient-billing/monthly-op-consultation-report",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 918,
              title: "Acknowledge Scroll Amount Report",
              defaultPath:
                "/out-patient-billing/acknowledged-scroll-amount-report",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 579,
              title: "Expired Deposits",
              defaultPath: "/out-patient-billing/expired-deposits",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 920,
              title: "Online Deposit Report",
              defaultPath: "/out-patient-billing/online-deposit-report",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 67,
              title: "Dispatch Report",
              defaultPath: "/out-patient-billing/dispatch-report",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 67,
              title: "CRPS Orders Report",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
              locationSpecific: [
                { loc: 8 },
                { loc: 7 },
                { loc: 10 },
                { loc: 12 },
                { loc: 15 },
                { loc: 16 },
                { loc: 17 },
                { loc: 18 },
                { loc: 21 },
              ],
            },
            {
              id: 67,
              title: "Visit Report",
              defaultPath: "/report/prompt-report/VisitReport",
              globalSearchKey: "global",
              allUsersAllow: false,
              locationSpecific: [
                { loc: 8 },
                { loc: 7 },
                { loc: 10 },
                { loc: 12 },
                { loc: 15 },
                { loc: 16 },
                { loc: 17 },
                { loc: 18 },
                { loc: 21 },
              ],
            },
            {
              id: 67,
              title: "eCare Op Summary Report ",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
              locationSpecific: [
                { loc: 8 },
                { loc: 7 },
                { loc: 10 },
                { loc: 12 },
                { loc: 15 },
                { loc: 16 },
                { loc: 17 },
                { loc: 18 },
                { loc: 21 },
              ],
            },
          ],
          moreOptions: true,
        },
        {
          id: -1,
          title: "MIME",
          defaultPath: "",
          childrens: [],
          moreOptions: false,
        },
      ],
    },
    {
      title: "Emergency",
      id: 32,
      defaultPath: "",
      childrens: [],
      type: "module",
    },
    {
      title: "In-Patients",
      id: 1,
      defaultPath: "",
      childrens: [],
    },
    {
      title: "MMS",
      id: 3,
      defaultPath: "",
      childrens: [],
    },
    {
      title: "Operation Theater",
      id: 5,
      defaultPath: "",
      childrens: [],
      type: "module",
    },
    {
      title: "MIS reports",
      id: 34,
      defaultPath: "/mis-reports",
      moreOptions: true,
      childrens: [
        {
          id: -1,
          title: "OP/IP",
          defaultPath: "",
          moreOptions: true,
          tenentPath: "/mis-reports",
          childrens: [
            {
              id: 60,
              title: "IP",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
              childrens: [
                {
                  id: 60,
                  title: "Billing",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [
                    {
                      id: 60,
                      title: "Discount Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 60,
                      title: "Refund Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 60,
                      title: "Inter Organization Transfer report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 60,
                      title: "Inter Organization Transfer Report Service wise",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 60,
                      title:
                        "Surgery breakup details for Inter Organization Transfer",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 60,
                      title:
                        "Cancelled Investigations after Acknowledgement Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 60,
                      title: "Unified Emergency Transfer service wise Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 60,
                      title: "Estimation Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 60,
                      title: "Surgical estimation variance analysis Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 60,
                  title: "Patient Reports",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "Sparsh",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "MIS",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "IP Sales Register",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "IP Sales Register for Month",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "IP TPA Revenue Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "IP Corporate Revenue Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "IP Package Detail Revenue Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "Ward Wise BedType Wise Service Wise Revenue",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "Miscellaneous Bills report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "Miscellaneous Bills report New",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "IP Bill Register",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "IP Bill Detail Register",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "Triage Bill Register",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "Operational Readiness MIS Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "Dashboard",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "Estimation Reports",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 60,
                  title: "Exception Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
              ],
            },
            {
              id: 60,
              title: "OP",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 60,
              title: "Common",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 60,
              title: "BI Reports",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
          ],
        },
        {
          id: -1,
          title: "Marketing",
          defaultPath: "",
          moreOptions: true,
          tenentPath: "/mis-reports",
          childrens: [],
        },
        {
          id: -1,
          title: "MMS",
          defaultPath: "",
          moreOptions: true,
          tenentPath: "/mis-reports",
          childrens: [],
        },
      ],
      type: "module",
    },
    {
      title: "Physicians",
      id: 5,
      defaultPath: "",
      childrens: [],
    },
    {
      title: "Laboratory",
      id: 4,
      defaultPath: "",
      childrens: [],
    },
    {
      title: "Adverse Events",
      id: 42,
      defaultPath: "",
      childrens: [],
      type: "module",
    },
    {
      title: "Donate Blood",
      id: 11,
      defaultPath: "",
      childrens: [],
    },
    {
      title: "Administration",
      id: 6,
      defaultPath: "",
      childrens: [],
    },
  ];

  export function getModules() {
    return modules;
  }
}
