export namespace MaxModules {
  const modules = [
    {
      title: "Dashboard",
      id: 0,
      defaultPath: "/dashboard",
      moreOptions: false,
      globalSearchKey: "global",
      childrens: [],
      dontShow: true,
      allUsersAllow: false,
    },
    {
      title: "Out Patients",
      id: 7,
      defaultPath: "/out-patients",
      moreOptions: true,
      type: "module",
      childrens: [
        {
          id: -1,
          title: "Registration",
          defaultPath: "registration",
          moreOptions: true,
          tenentPath: "/out-patients",
          childrens: [
            {
              id: 60,
              title: "OP Registration",
              defaultPath: "/registration/op-registration",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 61,
              title: "Find Patient",
              defaultPath: "/registration/find-patient",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 460,
              title: "Duplicate Reg Merging",
              defaultPath: "/registration/dup-reg-merging",
              globalSearchKey: "merge",
              allUsersAllow: true,
            },
            {
              id: 461,
              title: "Registration Unmerging",
              defaultPath: "/registration/registration-unmerging",
              globalSearchKey: "unmerge",
              allUsersAllow: true,
            },
            {
              id: 60,
              title: "Registration Modification",
              defaultPath: "/registration/op-registration",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 595,
              title: "OP Patient Reg Approval List",
              defaultPath: "/registration/op-reg-approval",
              globalSearchKey: "opapproval",
              allUsersAllow: false,
            },
            {
              id: 597,
              title: "Hot Listing Approval",
              defaultPath: "/registration/hot-listing-approval",
              globalSearchKey: "opapproval",
              allUsersAllow: false,
            },
            {
              id: 27118,
              title: "Bulk Upload Registration",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 27119,
              title: "Search Patient Admit/Discharge",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 27120,
              title: "Report for Bulk Upload Reg",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 27121,
              title: "For Ambulance and Reg Charges",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 27122,
              title: "Blood Group Entry",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
          ],
        },
        {
          id: -1,
          title: "Out Patient Billing",
          defaultPath: "out-patient-billing",
          tenentPath: "/out-patients",
          childrens: [
            {
              id: 62,
              title: "Out Patient Billing",
              defaultPath: "/out-patient-billing/",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 64,
              title: "Deposit",
              defaultPath: "/out-patient-billing/deposit",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 63,
              title: "Bill Details",
              defaultPath: "/out-patient-billing/details",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 214,
              title: "Online Generated OP Bills",
              defaultPath: "/out-patient-billing/online-op-bill",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 215,
              title: "OP Order Request",
              defaultPath: "/out-patient-billing/op-order-request",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 216,
              title: "Miscellaneous Billing",
              defaultPath: "/out-patient-billing/miscellaneous-billing",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 217,
              title: "Initiate Deposit",
              defaultPath: "/out-patient-billing/initiate-deposit",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 218,
              title: "OP Refund Approval",
              defaultPath: "/out-patient-billing/op-refund-approval",
              globalSearchKey: "opapproval",
              allUsersAllow: true,
            },
            {
              id: 219,
              title: "DMG Mapping",
              defaultPath: "/out-patient-billing/dmg-mapping",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 62,
              title: "Post Discharge Follow Up Billing",
              defaultPath:
                "/out-patient-billing/post-discharge-follow-up-billing",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            // dispatch
            {
              id: 222,
              title: "Expired Patient Check",
              defaultPath: "/out-patient-billing/expired-patient-check",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
          ],
          moreOptions: true,
        },
        {
          id: -1,
          title: "ACD",
          tenentPath: "/out-patients",
          defaultPath: "/acd/investigation-orders",
          childrens: [],
          moreOptions: false,
        },
        {
          id: -1,
          title: "Patient History",
          tenentPath: "/out-patients",
          defaultPath: "/patient-history",
          childrens: [],
          moreOptions: false,
        },
        {
          id: -1,
          title: "Configure",
          tenentPath: "/out-patients",
          defaultPath: "",
          childrens: [
            {
              id: 223,
              title: "Regenerate RIS Message",
              defaultPath: "/configure/RIS",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 224,
              title: "Regenerate LIMS Message",
              defaultPath: "/configure/LIMS",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
          ],
          moreOptions: true,
        },
        {
          id: -1,
          title: "QMS",
          tenentPath: "/out-patients",
          defaultPath: "/qms",
          childrens: [],
          moreOptions: false,
        },
        {
          id: -1,
          title: "Staff Dependents",
          tenentPath: "/out-patients",
          defaultPath: "/staff-dept",
          childrens: [],
          moreOptions: false,
        },
        {
          id: -1,
          title: "Employee Sponsor Tagging",
          tenentPath: "/out-patients",
          defaultPath: "/employee-sponsor-tagging",
          childrens: [],
          moreOptions: false,
          locationSpecific: [{ loc: 69 }],
          globalSearchKey: "employeesponsor",
        },
        {
          id: -1,
          title: "Reports",
          tenentPath: "/out-patients",
          defaultPath: "report",
          childrens: [
            {
              id: 83,
              title: "Doctor Schedule",
              defaultPath: "/report/prompt-report/doctorSchedule",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 66,
              title: "Cash Scroll",
              defaultPath: "/out-patient-billing/cash-scroll",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 85,
              title: "Happy Family Report",
              defaultPath:
                "/report-multiple/prompt-report/HappyFamilyPlanAllocationReport",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 88,
              title: "Equipment Schedule",
              defaultPath: "/report/prompt-report/equipmentSchedule",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 89,
              title: "General OPD Scroll Report",
              defaultPath: "/report/prompt-report/GeneralOPDReport",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 916,
              title: "Expired Patient Report",
              defaultPath:
                "/report/prompt-report/CRPExpiredPatientDetailReport",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 917,
              title: "Monthly OP Consultation Report",
              defaultPath:
                "/out-patient-billing/monthly-op-consultation-report",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 918,
              title: "Acknowledge Scroll Amount Report",
              defaultPath:
                "/out-patient-billing/acknowledged-scroll-amount-report",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 579,
              title: "Expired Deposits",
              defaultPath: "/out-patient-billing/expired-deposits",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 920,
              title: "Online Deposit Report",
              defaultPath: "/out-patient-billing/online-deposit-report",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
            {
              id: 67,
              title: "Dispatch Report",
              defaultPath: "/out-patient-billing/dispatch-report",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 67,
              title: "CRPS Orders Report",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
              locationSpecific: [
                { loc: 8 },
                { loc: 7 },
                { loc: 10 },
                { loc: 12 },
                { loc: 15 },
                { loc: 16 },
                { loc: 17 },
                { loc: 18 },
                { loc: 21 },
              ],
            },
            {
              id: 67,
              title: "Visit Report",
              defaultPath: "/report/prompt-report/VisitReport",
              globalSearchKey: "global",
              allUsersAllow: false,
              locationSpecific: [
                { loc: 8 },
                { loc: 7 },
                { loc: 10 },
                { loc: 12 },
                { loc: 15 },
                { loc: 16 },
                { loc: 17 },
                { loc: 18 },
                { loc: 21 },
              ],
            },
            {
              id: 67,
              title: "eCare Op Summary Report ",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
              locationSpecific: [
                { loc: 8 },
                { loc: 7 },
                { loc: 10 },
                { loc: 12 },
                { loc: 15 },
                { loc: 16 },
                { loc: 17 },
                { loc: 18 },
                { loc: 21 },
              ],
            },
          ],
          moreOptions: true,
        },
        {
          id: -1,
          title: "MIME",
          defaultPath: "",
          childrens: [],
          moreOptions: false,
        },
      ],
    },
    {
      title: "Emergency",
      id: 32,
      defaultPath: "",
      childrens: [],
      type: "module",
    },
    {
      title: "In-Patients",
      id: 1,
      defaultPath: "",
      childrens: [],
    },
    {
      title: "MMS",
      id: 3,
      defaultPath: "/mms",
      moreOptions: true,
      type: "module",
      childrens: [
        {
          id: -1,
          title: "Materials",
          defaultPath: "",
          moreOptions: true,
          tenentPath: "/mms",
          childrens: [],
        },
        {
          id: -1,
          title: "Pharmacy",
          defaultPath: "",
          tenentPath: "/mms",
          childrens: [
            {
              id: 62,
              title: "OP Pharmacy",
              defaultPath: "oppharmacy",
              globalSearchKey: "global",
              allUsersAllow: false,
              moreOptions: true,
              tenentPath: "/mms",
              childrens: [
                {
                  id: 60,
                  title: "Issue / Credit",
                  defaultPath: "/oppharmacy/issue",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
                {
                  id: 61,
                  title: "Returns",
                  defaultPath: "/oppharmacy/returns",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
                {
                  id: 460,
                  title: "Due bill settlement",
                  defaultPath: "/oppharmacy/due-bill-settlement",
                  globalSearchKey: "global",
                  allUsersAllow: true,
                },
                {
                  id: 461,
                  title: "Home delivery due report",
                  defaultPath: "/oppharmacy/home-delivery-due",
                  globalSearchKey: "unmerge",
                  allUsersAllow: true,
                },
              ],
            },
            {
              id: 64,
              title: "IP Pharmacy",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 63,
              title: "Master",
              defaultPath: "/pharmacy/masters",
              globalSearchKey: "global",
              allUsersAllow: false,
            },
            {
              id: 214,
              title: "Staff Dependent",
              defaultPath: "/pharmacy/staffdependent",
              globalSearchKey: "global",
              allUsersAllow: true,
            },
          ],
          moreOptions: true,
        },
        {
          id: -1,
          title: "Non Medical items",
          tenentPath: "/out-patients",
          defaultPath: "/mms/non-medical-items",
          childrens: [],
          moreOptions: false,
        },
      ],
    },
    {
      title: "Operation Theater",
      id: 5,
      defaultPath: "",
      childrens: [],
      type: "module",
    },
    {
      title: "MIS reports",
      id: 34,
      defaultPath: "/mis-reports",
      moreOptions: true,
      childrens: [
        {
          id: 34,
          title: "OP/IP",
          defaultPath: "/op-ip",
          moreOptions: true,
          tenentPath: "/mis-reports",
          childrens: [
            {
              id: 34,
              title: "IP",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
              tenentPath: "/mis-reports",
              childrens: [
                {
                  id: 34,
                  title: "Billing",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "Discount Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Refund Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Inter Organization Transfer report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Inter Organization Transfer Report Service wise",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title:
                        "Surgery breakup details for Inter Organization Transfer",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title:
                        "Cancelled Investigations after Acknowledgement Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Unified Emergency Transfer service wise Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Estimation Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Surgical estimation variance analysis Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "Patient Reports",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "IP Discharged Patient Discount Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Admission Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Discharge Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Current in Patient Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Census Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Bed Status Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Package Status Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Procedure Summary",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Patient Expiry Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Cancel Discharge Patient Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Discharge Patient Template",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "IPDischarge Patient Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Reason For Admission",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Cancel Admission Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "Sparsh",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [
                    {
                      id: 34,
                      title: "Timeliness of IPD Reports Delivery",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "MIS",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "Outside India Patients",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "IP Sales Register",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "IP Sales Register for Month",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "IP TPA Revenue Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "IP Corporate Revenue Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "IP Package Detail Revenue Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "Ward Wise BedType Wise Service Wise Revenue",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "Miscellaneous Bills report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "Miscellaneous Bills report New",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "IP Bill Register",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "IP Bill Detail Register",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "Triage Bill Register",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "Operational Readiness MIS Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  childrens: [],
                },
                {
                  id: 34,
                  title: "Dashboard",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "TPA Patients Admitted Reports",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "All Channels Admitted Patient Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Operational Readiness Dashboard",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "Estimation Reports",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "IP Wise Estimation(During Admission)",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "IP Wise Estimation(Post Discharge)",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Estimation Status Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "Exception Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "Emergency Exception Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Exceeding Medication Amount > 5 K",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
              ],
            },
            {
              id: 34,
              title: "OP",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
              tenentPath: "/mis-reports",
              childrens: [
                {
                  id: 34,
                  title: "Billing",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "Scroll Summary Report",
                      defaultPath: "/op-ip/prompt-report/ScrollSummaryReport",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Refund Report",
                      defaultPath: "/op-ip/prompt-report/opRefundReport",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Discount Report",
                      defaultPath: "/op-ip/prompt-report/discountReport",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Free Out Patient Report",
                      defaultPath: "/op-ip/prompt-report/freeOutPatientReport",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "Corporate",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "Corporate Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Corporate Item Wise Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Corporate Patient Wise Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Corporate TPA Revenue Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "Medical Record",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "Doctor Consultation Detail",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "New Old Patient Visit (Consultation Wise)",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Episode Doctor Procedure Wise Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Consults",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Doctor Wise Procedure",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Diagnotics",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Referral Doctor All (External)",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Referral Doctor All Detail(External)",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Department Wise Referral Revenue",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title:
                        "Episode Doctor Procedure wise report(Sorted On Bill No)",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "PHC",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "Preventive Health Check Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "PHC Detail Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "PHC Sorting Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Report Sorting",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Investigation Booking",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "PHC COMPARISION REPORT",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "Sparsh",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "Patient Visits Time wise",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "OP Sales Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
                {
                  id: 34,
                  title: "MIS",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "Flash",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "New Old Patients",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Pathology Report Status",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Test and Parameter",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Test and Parameter (Notes)",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Service wise Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Pharmacy Discount Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Miscellaneous Service Wise Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "Miscellaneous Bill Report",
                  defaultPath: "/op-ip/prompt-report/MiscellaneousMISReport",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
                {
                  id: 34,
                  title: "Miscellaneous Bill Report New",
                  defaultPath:
                    "/op-ip/prompt-report/miscellaneousBillingReportNew",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
                {
                  id: 34,
                  title: "OP Bill Register",
                  defaultPath: "/op-ip/prompt-report/opBillRegister",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
                {
                  id: 34,
                  title: "Price Modification Report",
                  defaultPath:
                    "/op-ip/prompt-report/CROPItemPriceModifiedReport",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
              ],
            },
            {
              id: 34,
              title: "Common",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
              tenentPath: "/mis-reports",
              childrens: [
                {
                  id: 34,
                  title: "MIS",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                  tenentPath: "/mis-reports",
                  childrens: [
                    {
                      id: 34,
                      title: "Department Wise Test and Revenue",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "YTD Month Countrywise Details",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Doctor Wise consults",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Test Done Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "IP-OP Nuclear Medicine Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Consumables",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Inter HUB Utilization Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title:
                        "Department Wise Sub Department Wise Revenue Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Procedure Doctor Report for OutPatients",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title:
                        "Procedure Doctor Report for Preadmission/Emergency",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Open Scroll Amount",
                      defaultPath: "/op-ip/prompt-report/OpenScrollReport",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Lab Referal wise Test and Revenue Report",
                      defaultPath: "",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                    {
                      id: 34,
                      title: "Service Tax Report",
                      defaultPath: "/op-ip/prompt-report/ServiceTaxReportData",
                      globalSearchKey: "global",
                      allUsersAllow: false,
                    },
                  ],
                },
                {
                  id: 34,
                  title: "OP/IP Price List",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
                {
                  id: 34,
                  title: "Equipment Charges Report",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
                {
                  id: 34,
                  title: "Daily Collection Report",
                  defaultPath: "/op-ip/prompt-report/DailyCollectionReport",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
                {
                  id: 34,
                  title: "Online Payment Detail Report",
                  defaultPath: "/op-ip/prompt-report/OnlinePaymentDetailReport",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
              ],
            },
            {
              id: 34,
              title: "BI Reports",
              defaultPath: "",
              globalSearchKey: "global",
              allUsersAllow: false,
              tenentPath: "/mis-reports",
              childrens: [
                {
                  id: 34,
                  title: "BI Reports",
                  defaultPath: "",
                  globalSearchKey: "global",
                  allUsersAllow: false,
                },
              ],
            },
          ],
        },
        {
          id: 38,
          title: "Marketing",
          defaultPath: "/marketing",
          moreOptions: false,
          tenentPath: "/mis-reports",
          childrens: [],
        },
        {
          id: 35,
          title: "MMS",
          defaultPath: "/mms",
          moreOptions: false,
          tenentPath: "/mis-reports",
          childrens: [],
        },
      ],
      type: "module",
    },
    {
      title: "Physicians",
      id: 5,
      defaultPath: "",
      childrens: [],
    },
    {
      title: "Laboratory",
      id: 4,
      defaultPath: "",
      childrens: [],
    },
    {
      title: "Adverse Events",
      id: 42,
      defaultPath: "",
      childrens: [],
      type: "module",
    },
    {
      title: "Donate Blood",
      id: 11,
      defaultPath: "",
      childrens: [],
    },
    {
      title: "Administration",
      id: 6,
      defaultPath: "",
      childrens: [],
    },
  ];

  export function getModules() {
    return modules;
  }
}
