export interface onlinedeposit{
    id: any,
    iaCode: any,
    maxid?: any,
    registrationno: any,
    eMailID: any,
    mobileNo: any,
    depositType: any,
    amount: any,
    stationName: any,
    statusCode: any,
    statusDesc: any,
    createDate: any,
    depositSource: any,
    initDep_DateTime: any,
    initDep_Response_ID: any,
    pay_Or_PayCheck_Date: any,
    pay_reference_no: any,
    pay_bank_ref_no: any,
    hiS_UpdateDateTime: any,
    hiS_DepositID: any,
    receiptNo: any,
    initDep_OtherDetail: any,
}